version: '3'
services:
  db:
    image: mysql:8.0.23
    environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: foodpicker
        MYSQL_USER: hami
        # only change the password by the firstime
        MYSQL_PASSWORD: secret
    ports:
      - 3306:3306
    networks:
      - symfony
    volumes:
      - dbdata:/var/lib/mysql
  php:
    build:
      context: ./docker/php
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ./foodpicker:/var/www/foodpicker/
    networks:
      - symfony
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./foodpicker:/var/www/foodpicker/
    ports:
      - 8080:80
    networks:
      - symfony

networks:
  symfony:
volumes:
    dbdata:
      driver: local