version: '3'

services:
  database:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: foodpicker
#      MYSQL_USER: root
#      MYSQL_PASSWORD: root
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - internal
    ports:
      - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    depends_on:
      - database
    ports:
      - 8082:80
    networks:
      - internal
    environment:
      - PMA_ARBITRARY=1

  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www/foodpicker
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
    ports:
      - 8080:80
    networks:
      - internal

  php:
    build:
      context: .
    ports:
      - '9000:9000'
    volumes:
      - .:/var/www/foodpicker
    depends_on:
      - database
    networks:
      - internal


networks:
  internal:
    driver: bridge
volumes:
  ###> doctrine/doctrine-bundle ###
  dbdata:
###< doctrine/doctrine-bundle ###
